function settings_fcn = FrequencySweepGUI(parent, bottom, left, name)
% FREQUENCYSWEEP_BUILD
%-------------------------------------------------------------------------------
% File name   : FrequencySweep_build.m        
% Generated on: 15-Oct-2010 15:05:05          
% Description :
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();


% if there is no parent figure given, generate one
if nargin < 1 || ~isnumeric(parent)
	handles.figure1 = figure( ...
			'Tag', 'figure1', ...
			'Units', 'characters', ...
			'Position', [103.833333333333 13.8571428571429 78 12], ...
			'Name', 'Frequency Settings', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));
	
	left = 10.0;
	bottom = 10.0;
	name = ['Frequency settings'];
else
	handles.figure1 = parent;
	name = ['Frequency settings ' name];
end

% Create all UI controls
build_gui();

% Assign function output
settings_fcn = @get_settings;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- PANELS -------------------------------------
		handles.uipanel1 = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'uipanel1', ...
			'Units', 'pixels', ...
			'Position', [left bottom 425 115], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'Title', name);

		% --- STATIC TEXTS -------------------------------------
		handles.text1 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text1', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.8 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Start frequency (GHz)');

		handles.text2 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [24 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Stop frequency (GHz)');

		handles.text3 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [46.8 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Step frequency (GHz)');

		handles.text4 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text4', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.8 5.72527472527473 12.8 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Generator ID');

% 		handles.text5 = uicontrol( ...
% 			'Parent', handles.uipanel1, ...
% 			'Tag', 'text5', ...
% 			'Style', 'text', ...
% 			'Units', 'characters', ...
% 			'Position', [27.6 5.72527472527473 13.4 1.07692307692308], ...
% 			'FontName', 'Helvetica', ...
% 			'FontSize', 10, ...
% 			'BackgroundColor', [0.878 0.875 0.89], ...
% 			'String', 'Power (dBm)');

		% --- EDIT TEXTS -------------------------------------
		handles.startFreq = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'startFreq', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [2.8 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '10');

		handles.stopFreq = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'stopFreq', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [25 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '10');

		handles.stepFreq = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'stepFreq', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [47.8 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '0.001');

% 		handles.power = uicontrol( ...
% 			'Parent', handles.uipanel1, ...
% 			'Tag', 'power', ...
% 			'Style', 'edit', ...
% 			'Units', 'characters', ...
% 			'Position', [29 3.8021978021978 11.2 1.53846153846154], ...
% 			'FontName', 'Helvetica', ...
% 			'FontSize', 10, ...
% 			'BackgroundColor', [1 1 1], ...
% 			'String', '-80');

		% --- POPUP MENU -------------------------------------
		handles.genID = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'genID', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [3 3.95604395604396 19 1.61538461538462], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'RF','LO','Spec'});


	end

	function selected = get_selected(hObject)
		menu = get(hObject,'String');
		selected = menu{get(hObject,'Value')};
	end

	function value = get_numeric(hObject)
		value = str2num(get(hObject, 'String'));
	end

	function settings = get_settings()
		settings = struct();
		
		settings.type = 'sweeps.Frequency';
		settings.start = get_numeric(handles.startFreq);
		settings.stop = get_numeric(handles.stopFreq);
		settings.step = get_numeric(handles.stepFreq);
		settings.genID = [get_selected(handles.genID) 'gen'];
	end

end
