function settings_fcn = TekChannelSweepGUI(parent, bottom, left, name)
% FREQUENCYSWEEP_BUILD
%-------------------------------------------------------------------------------
% File name   : FrequencySweep_build.m        
% Generated on: 15-Oct-2010 15:05:05          
% Description :
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();


% if there is no parent figure given, generate one
if nargin < 1 || ~isnumeric(parent)
	handles.figure1 = figure( ...
			'Tag', 'figure1', ...
			'Units', 'characters', ...
			'Position', [103.833333333333 13.8571428571429 78 12], ...
			'Name', 'Tek Channel Settings', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));
	
	left = 10.0;
	bottom = 10.0;
	name = ['Tek channel settings'];
else
	handles.figure1 = parent;
	name = ['Tek channel settings ' name];
end

% Create all UI controls
build_gui();

% Assign function output
settings_fcn = @get_settings;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- PANELS -------------------------------------
		handles.uipanel1 = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'uipanel1', ...
			'Units', 'pixels', ...
			'Position', [left bottom 425 115], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'Title', name);

		% --- STATIC TEXTS -------------------------------------
		handles.text1 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text1', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.8 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Start level (V)');

		handles.text2 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [24 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Stop level (V)');

		handles.text3 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [46.8 2.26373626373626 22 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Step (V)');

		handles.text4 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text4', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.8 5.72527472527473 12.8 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Type');

		handles.text5 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text5', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [27.6 5.72527472527473 13.4 1.07692307692308], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'String', 'Channel');

		% --- EDIT TEXTS -------------------------------------
		handles.start = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'start', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [2.8 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.stop = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'stop', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [25 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.step = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'step', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [47.8 0.725274725274725 19.4 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.channel = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'channel', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [29 3.8021978021978 11.2 1.53846153846154], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		% --- POPUP MENU -------------------------------------
		handles.ampOffset = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ampOffset', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [3 3.95604395604396 19 1.61538461538462], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'Amp','Offset'});


	end

	function selected = get_selected(hObject)
		menu = get(hObject,'String');
		selected = menu{get(hObject,'Value')};
	end

	function value = get_numeric(hObject)
		value = str2num(get(hObject, 'String'));
	end

	function settings = get_settings()
		settings = struct();
		
		settings.type = 'sweeps.TekChannel';
		settings.start = get_numeric(handles.start);
		settings.stop = get_numeric(handles.stop);
		settings.step = get_numeric(handles.step);
        settings.channel = get_numeric(handles.channel);
		settings.ampOffset = get_selected(handles.ampOffset);
	end

end
