function settings_fcn = APS_settings_GUI(parent, bottom, left, name, settings)
%-------------------------------------------------------------------------------
% File name   : APS_settings_GUI.m               
% Description : Copies from AWG5014_settings_GUI with minor modifications
%-------------------------------------------------------------------------------

pmval_to_sample_rate = [1200,600,300,100,40];

% Initialize handles structure
handles = struct();

% if there is no parent figure given, generate one
if nargin < 1 || ~isnumeric(parent)
	handles.figure1 = figure( ...
			'Tag', 'figure1', ...
			'Units', 'characters', ...
			'Position', [103.833333333333 13.8571428571429 90 20], ...
			'Name', 'BBN APS Settings', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));
	
	left = 10.0;
	bottom = 10.0;
	name = ['BBN APS settings'];
else
	handles.figure1 = parent;
	name = [name ' settings'];
end

% Create all UI controls
build_gui();

if nargin < 5
	settings = struct();
end
set_defaults(settings);

% Assign function output
settings_fcn = @get_settings;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- PANELS -------------------------------------
		handles.uipanel1 = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'uipanel1', ...
			'UserData', zeros(1,0), ...
			'Units', 'pixels', ...
			'Position', [left bottom 390 220], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'Title', name);

		% --- STATIC TEXTS -------------------------------------
		handles.text1 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text1', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.00000000000001 14.0769230769231 5 0.923076923076923], ...
			'String', 'Ch1');

		handles.text2 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [17.4 14.0769230769231 5 0.923076923076923], ...
			'String', 'Ch2');

		handles.text3 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [25.8 14.1538461538461 5 0.923076923076923], ...
			'String', 'Ch3');

		handles.text4 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text4', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [34.6000000000001 14.0769230769231 5 0.923076923076923], ...
			'String', 'Ch4');

		handles.text5 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text5', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.93333333333333 2.53846153846153 10 0.928571428571429], ...
			'String', 'DevID');

		handles.text8 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text8', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.73333333333334 6.28021978021977 20 0.928571428571429], ...
			'String', 'Sequence File', ...
			'HorizontalAlignment', 'left');

		handles.text9 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text9', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [60.6 10.5384615384615 15 1], ...
			'String', 'Samp. Rate');

% 		handles.text10 = uicontrol( ...
% 			'Parent', handles.uipanel1, ...
% 			'Tag', 'text10', ...
% 			'Style', 'text', ...
% 			'Units', 'characters', ...
% 			'Position', [54.8 8.84615384615384 7 0.923076923076923], ...
% 			'String', '(GS/s)', ...
% 			'HorizontalAlignment', 'left');

		handles.text11 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text11', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [59 14.2307692307692 15 1], ...
			'String', 'Trigger');

% 		handles.text13 = uicontrol( ...
% 			'Parent', handles.uipanel1, ...
% 			'Tag', 'text13', ...
% 			'Style', 'text', ...
% 			'Units', 'characters', ...
% 			'Position', [60.6 10.5384615384615 15 1], ...
% 			'String', 'Trig Interval');

		handles.text14 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text14', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.06666666666667 12.6923076923077 6 1], ...
			'String', 'Amp');

		handles.text15 = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'text15', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1.06666666666667 10.7637362637363 6 1], ...
			'String', 'Off.');

% 		handles.text16 = uicontrol( ...
% 			'Parent', handles.uipanel1, ...
% 			'Tag', 'text16', ...
% 			'Style', 'text', ...
% 			'Units', 'characters', ...
% 			'Position', [71.0000000000001 8.76923076923077 3 0.923076923076923], ...
% 			'String', '(s)', ...
% 			'HorizontalAlignment', 'left');

		% --- RADIO BUTTONS -------------------------------------
		handles.ch1enable = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch1enable', ...
			'Style', 'radiobutton', ...
			'Units', 'pixels', ...
			'Position', [46 108.642857142857 40 17], ...
			'String', 'On');

		handles.ch2enable = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch2enable', ...
			'Style', 'radiobutton', ...
			'Units', 'pixels', ...
			'Position', [90 108.642857142857 40 17], ...
			'String', 'On');

		handles.ch3enable = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch3enable', ...
			'Style', 'radiobutton', ...
			'Units', 'pixels', ...
			'Position', [133 108.642857142857 40 17], ...
			'String', 'On');

		handles.ch4enable = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'seqfile', ...
			'Style', 'radiobutton', ...
			'Units', 'pixels', ...
			'Position', [175 108.642857142857 40 17], ...
			'String', 'On');

		% --- CHECKBOXES -------------------------------------
		handles.enable = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'enable', ...
			'Style', 'checkbox', ...
			'Units', 'pixels', ...
			'Position', [76 13.6428571428569 65 17], ...
			'String', 'Enable');

		handles.seqforce = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'seqforce', ...
			'Style', 'checkbox', ...
			'Units', 'pixels', ...
			'Position', [288 37.9999999999999 65 17], ...
			'String', 'Force');

		% --- EDIT TEXTS -------------------------------------
		handles.ch1amp = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch1amp', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [41 159.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch1off = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch1off', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [41 132.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch2amp = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch2amp', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [85 159.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch2off = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch2off', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [85 132.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch3amp = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch3amp', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [128 159.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch3off = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch3off', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [128 132.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch4amp = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch4amp', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [170 159.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.ch4off = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'ch4off', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [170 132.642857142857 35 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.seqfile = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'edit11', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [13 57.6428571428569 325 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		handles.devID = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'gpibAddress', ...
			'Style', 'edit', ...
			'Units', 'pixels', ...
			'Position', [13 10.6428571428569 50 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', '');

		% --- POPUP MENU -------------------------------------
        handles.samplingRate = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'samplingRate', ...
			'Style', 'popupmenu', ...
			'Units', 'pixels', ...
			'Position', [312 110.642857142857 65 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', {'1.2 GHz'; '600 MHz'; '300 MHz'; '100 MHz'; '40 MHz'});

		handles.triggerSource = uicontrol( ...
			'Parent', handles.uipanel1, ...
			'Tag', 'triggerSource', ...
			'Style', 'popupmenu', ...
			'Units', 'pixels', ...
			'Position', [312 162 50 22], ...
			'BackgroundColor', [1 1 1], ...
			'String', {'Ext','Int'});


	end

	function selected = get_selected(hObject)
		menu = get(hObject,'String');
		selected = menu{get(hObject,'Value')};
    end

	function set_selected(hObject, val)
		menu = get(hObject, 'String');
		index = find(strcmp(val, menu));
		if ~isempty(index)
			set(hObject, 'Value', index);
		end
	end

	function value = get_numeric(hObject)
		value = str2num(get(hObject, 'String'));
	end

	function settings = get_settings()
		settings = struct();
		
		settings.enable = get(handles.enable, 'Value');
		settings.deviceName = 'Tek5014';
		settings.Address = get(handles.devID, 'String');

		settings.scaleMode = get_selected(handles.scaleMode);

		settings.chan_1.amplitude = get_numeric(handles.ch1amp);
		settings.chan_1.offset = get_numeric(handles.ch1off);
		settings.chan_1.enabled = get(handles.ch1enable, 'Value');
		settings.chan_2.amplitude = get_numeric(handles.ch2amp);
		settings.chan_2.offset = get_numeric(handles.ch2off);
		settings.chan_2.enabled = get(handles.ch2enable, 'Value');
		settings.chan_3.amplitude = get_numeric(handles.ch3amp);
		settings.chan_3.offset = get_numeric(handles.ch3off);
		settings.chan_3.enabled = get(handles.ch3enable, 'Value');
		settings.chan_4.amplitude = get_numeric(handles.ch4amp);
		settings.chan_4.offset = get_numeric(handles.ch4off);
		settings.chan_4.enabled = get(handles.ch4enable, 'Value');
		settings.seqfile = get(handles.seqfile, 'String');
		settings.seqforce = get(handles.seqforce, 'Value');
		settings.triggerSource = get_selected(handles.triggerSource);
		settings.samplingRate = pmval_to_sample_rate(get(handles.samplingRate, 'Value'));
		
    end

	function set_defaults(settings)
		% define default values for fields. If given a settings structure, grab
		% defaults from it
		defaults = struct();
		defaults.enable = 0;
		defaults.Address = 0;
        for i = 1:4
            channel = ['chan_' num2str(i)];
            defaults.(channel).amplitude = 1;
            defaults.(channel).offset = 0;
            defaults.(channel).enabled = 1;
        end
        defaults.seqfile = 'U:\APS\Trigger\Trigger.mat';
        defaults.seqforce = 0;
        defaults.triggerSource = 'Ext';
        defaults.samplingRate = 1200;

		if ~isempty(fieldnames(settings))
			fields = fieldnames(settings);
			for i = 1:length(fields)
				name = fields{i};
				defaults.(name) = settings.(name);
			end
		end
		
		set(handles.enable, 'Value', defaults.enable);
		set(handles.devID, 'String', num2str(defaults.Address));
        for i = 1:4
            channel = ['chan_' num2str(i)];
            set(handles.(['ch' num2str(i) 'amp']), 'String', defaults.(channel).amplitude);
            set(handles.(['ch' num2str(i) 'off']), 'String', defaults.(channel).offset);
            set(handles.(['ch' num2str(i) 'enable']), 'Value', defaults.(channel).enabled);
        end
		set(handles.seqfile, 'String', defaults.seqfile);
		set(handles.seqforce, 'Value', defaults.seqforce);
		set_selected(handles.triggerSource, defaults.triggerSource);
        index = find(pmval_to_sample_rate == defaults.samplingRate);
        if ~isempty(index)
            set(handles.samplingRate, 'Value', index);
        end
	end

end
