# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'APS.ui'
#
# Created: Tue Aug 09 09:46:36 2011
#      by: pyside-uic 0.2.12 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(738, 558)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.deviceID = QtGui.QComboBox(Dialog)
        self.deviceID.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deviceID.setObjectName("deviceID")
        self.deviceID.addItem("")
        self.horizontalLayout.addWidget(self.deviceID)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.configBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configBox.sizePolicy().hasHeightForWidth())
        self.configBox.setSizePolicy(sizePolicy)
        self.configBox.setMinimumSize(QtCore.QSize(0, 150))
        self.configBox.setObjectName("configBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.configBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.configBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.bitFileName = QtGui.QLineEdit(self.configBox)
        self.bitFileName.setMinimumSize(QtCore.QSize(0, 22))
        self.bitFileName.setObjectName("bitFileName")
        self.horizontalLayout_2.addWidget(self.bitFileName)
        self.bitFileOpen = QtGui.QPushButton(self.configBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bitFileOpen.sizePolicy().hasHeightForWidth())
        self.bitFileOpen.setSizePolicy(sizePolicy)
        self.bitFileOpen.setMinimumSize(QtCore.QSize(0, 32))
        self.bitFileOpen.setObjectName("bitFileOpen")
        self.horizontalLayout_2.addWidget(self.bitFileOpen)
        self.bitFileVersion = QtGui.QLabel(self.configBox)
        self.bitFileVersion.setObjectName("bitFileVersion")
        self.horizontalLayout_2.addWidget(self.bitFileVersion)
        self.programButton = QtGui.QPushButton(self.configBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programButton.sizePolicy().hasHeightForWidth())
        self.programButton.setSizePolicy(sizePolicy)
        self.programButton.setMinimumSize(QtCore.QSize(0, 32))
        self.programButton.setObjectName("programButton")
        self.horizontalLayout_2.addWidget(self.programButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.configBox)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.triggerType = QtGui.QComboBox(self.configBox)
        self.triggerType.setMinimumSize(QtCore.QSize(0, 26))
        self.triggerType.setObjectName("triggerType")
        self.triggerType.addItem("")
        self.triggerType.addItem("")
        self.horizontalLayout_5.addWidget(self.triggerType)
        self.label_8 = QtGui.QLabel(self.configBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sampleRate = QtGui.QComboBox(self.configBox)
        self.sampleRate.setMinimumSize(QtCore.QSize(0, 26))
        self.sampleRate.setObjectName("sampleRate")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.sampleRate.addItem("")
        self.horizontalLayout_5.addWidget(self.sampleRate)
        self.label_9 = QtGui.QLabel(self.configBox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.sequencerMode = QtGui.QComboBox(self.configBox)
        self.sequencerMode.setMinimumSize(QtCore.QSize(0, 26))
        self.sequencerMode.setObjectName("sequencerMode")
        self.sequencerMode.addItem("")
        self.sequencerMode.addItem("")
        self.horizontalLayout_5.addWidget(self.sequencerMode)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.runButton = QtGui.QPushButton(self.configBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(0, 32))
        self.runButton.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.runButton.setPalette(palette)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_13.addWidget(self.runButton)
        self.stopButton = QtGui.QPushButton(self.configBox)
        self.stopButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 32))
        self.stopButton.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_13.addWidget(self.stopButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.configBox)
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setTextFormat(QtCore.Qt.PlainText)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ch1file = QtGui.QLineEdit(self.tab)
        self.ch1file.setMinimumSize(QtCore.QSize(0, 22))
        self.ch1file.setObjectName("ch1file")
        self.horizontalLayout_4.addWidget(self.ch1file)
        self.ch1fileOpen = QtGui.QPushButton(self.tab)
        self.ch1fileOpen.setMinimumSize(QtCore.QSize(0, 32))
        self.ch1fileOpen.setObjectName("ch1fileOpen")
        self.horizontalLayout_4.addWidget(self.ch1fileOpen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.ch1scale = QtGui.QLineEdit(self.tab)
        self.ch1scale.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch1scale.setObjectName("ch1scale")
        self.horizontalLayout_3.addWidget(self.ch1scale)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.ch1offset = QtGui.QLineEdit(self.tab)
        self.ch1offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch1offset.setObjectName("ch1offset")
        self.horizontalLayout_3.addWidget(self.ch1offset)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.ch1enable = QtGui.QRadioButton(self.tab)
        self.ch1enable.setObjectName("ch1enable")
        self.horizontalLayout_3.addWidget(self.ch1enable)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.ch2file = QtGui.QLineEdit(self.tab_2)
        self.ch2file.setMinimumSize(QtCore.QSize(0, 22))
        self.ch2file.setObjectName("ch2file")
        self.horizontalLayout_8.addWidget(self.ch2file)
        self.ch2fileOpen = QtGui.QPushButton(self.tab_2)
        self.ch2fileOpen.setMinimumSize(QtCore.QSize(0, 32))
        self.ch2fileOpen.setObjectName("ch2fileOpen")
        self.horizontalLayout_8.addWidget(self.ch2fileOpen)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.ch2scale = QtGui.QLineEdit(self.tab_2)
        self.ch2scale.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch2scale.setObjectName("ch2scale")
        self.horizontalLayout_7.addWidget(self.ch2scale)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.ch2offset = QtGui.QLineEdit(self.tab_2)
        self.ch2offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch2offset.setObjectName("ch2offset")
        self.horizontalLayout_7.addWidget(self.ch2offset)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.ch2enable = QtGui.QRadioButton(self.tab_2)
        self.ch2enable.setObjectName("ch2enable")
        self.horizontalLayout_7.addWidget(self.ch2enable)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.ch3file = QtGui.QLineEdit(self.tab_3)
        self.ch3file.setMinimumSize(QtCore.QSize(0, 22))
        self.ch3file.setObjectName("ch3file")
        self.horizontalLayout_10.addWidget(self.ch3file)
        self.ch3fileOpen = QtGui.QPushButton(self.tab_3)
        self.ch3fileOpen.setMinimumSize(QtCore.QSize(0, 32))
        self.ch3fileOpen.setObjectName("ch3fileOpen")
        self.horizontalLayout_10.addWidget(self.ch3fileOpen)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.ch3scale = QtGui.QLineEdit(self.tab_3)
        self.ch3scale.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch3scale.setObjectName("ch3scale")
        self.horizontalLayout_9.addWidget(self.ch3scale)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.ch3offset = QtGui.QLineEdit(self.tab_3)
        self.ch3offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch3offset.setObjectName("ch3offset")
        self.horizontalLayout_9.addWidget(self.ch3offset)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.ch3enable = QtGui.QRadioButton(self.tab_3)
        self.ch3enable.setObjectName("ch3enable")
        self.horizontalLayout_9.addWidget(self.ch3enable)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.ch4file = QtGui.QLineEdit(self.tab_4)
        self.ch4file.setMinimumSize(QtCore.QSize(0, 22))
        self.ch4file.setObjectName("ch4file")
        self.horizontalLayout_12.addWidget(self.ch4file)
        self.ch4fileOpen = QtGui.QPushButton(self.tab_4)
        self.ch4fileOpen.setMinimumSize(QtCore.QSize(0, 32))
        self.ch4fileOpen.setObjectName("ch4fileOpen")
        self.horizontalLayout_12.addWidget(self.ch4fileOpen)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.ch4scale = QtGui.QLineEdit(self.tab_4)
        self.ch4scale.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch4scale.setObjectName("ch4scale")
        self.horizontalLayout_11.addWidget(self.ch4scale)
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.ch4offset = QtGui.QLineEdit(self.tab_4)
        self.ch4offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ch4offset.setObjectName("ch4offset")
        self.horizontalLayout_11.addWidget(self.ch4offset)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.ch4enable = QtGui.QRadioButton(self.tab_4)
        self.ch4enable.setObjectName("ch4enable")
        self.horizontalLayout_11.addWidget(self.ch4enable)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.messageLog = QtGui.QTextEdit(Dialog)
        self.messageLog.setReadOnly(True)
        self.messageLog.setObjectName("messageLog")
        self.verticalLayout.addWidget(self.messageLog)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_6.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Raytheon BBN Technologies APS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<b>Raytheon BBN Technologies Arbitrary Pulse Sequencer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Device ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceID.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.configBox.setTitle(QtGui.QApplication.translate("Dialog", "Device Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "FPGA Bit File:", None, QtGui.QApplication.UnicodeUTF8))
        self.bitFileOpen.setText(QtGui.QApplication.translate("Dialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.bitFileVersion.setText(QtGui.QApplication.translate("Dialog", "Firmware version: 16", None, QtGui.QApplication.UnicodeUTF8))
        self.programButton.setText(QtGui.QApplication.translate("Dialog", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Trigger Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerType.setItemText(0, QtGui.QApplication.translate("Dialog", "Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerType.setItemText(1, QtGui.QApplication.translate("Dialog", "External", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Sample Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRate.setItemText(0, QtGui.QApplication.translate("Dialog", "1.2 GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRate.setItemText(1, QtGui.QApplication.translate("Dialog", "600 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRate.setItemText(2, QtGui.QApplication.translate("Dialog", "300 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRate.setItemText(3, QtGui.QApplication.translate("Dialog", "100 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRate.setItemText(4, QtGui.QApplication.translate("Dialog", "40 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Sequencer Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencerMode.setItemText(0, QtGui.QApplication.translate("Dialog", "Continous", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencerMode.setItemText(1, QtGui.QApplication.translate("Dialog", "One shot", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("Dialog", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("Dialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Channel Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Waveform/Sequence file:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1fileOpen.setText(QtGui.QApplication.translate("Dialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Scale factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1enable.setText(QtGui.QApplication.translate("Dialog", "On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Channel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Waveform/Sequence file:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2fileOpen.setText(QtGui.QApplication.translate("Dialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Scale factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2enable.setText(QtGui.QApplication.translate("Dialog", "On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Channel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Waveform/Sequence file:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3fileOpen.setText(QtGui.QApplication.translate("Dialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Scale factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3enable.setText(QtGui.QApplication.translate("Dialog", "On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Channel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Waveform/Sequence file:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4fileOpen.setText(QtGui.QApplication.translate("Dialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Scale factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4enable.setText(QtGui.QApplication.translate("Dialog", "On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Channel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Message Log", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

