function AllXYlabel(h)
    % Function AllXYlabel(handle h)
    % inputs
    % h - figure handle (if none provided, assume the current figure)
    
    if nargin < 1
        h = gcf;
    end
    
    a = get(gcf,'CurrentAxes');
    xlabel(a, 'Pulse sequence')
    
    labels = {...
        'Id', ...
        'XpXm', ...
        'YpYm', ...
        'XpXp', ...
        'YpYp', ...
        'XpYp', ...
        'YpXp', ...
        'YpXm', ...
        'XpYm', ...
        ...
        'X90p', ...
        'Y90p', ...
        'X90m', ...
        'Y90m', ...
        'X90pY90p', ...
        'Y90pX90p', ...
        'X90mY90m', ...
        'Y90mX90m', ...
        'XpY90p', ...
        'YpX90p', ...
        'XpY90m', ...
        'YpX90m', ...
        'X90pYp', ...
        'Y90pXp', ...
        'XpX90p', ...
        'YpY90p', ...
        'XmX90m', ...
        'YmY90m', ...
        ...
        'Xp', ...
        'Xm', ...
        'Yp', ...
        'Ym', ...
        'X90pX90p', ...
        'X90mX90m', ...
        'Y90pY90p', ...
        'Y90mY90m', ...
        };
    
    % grab the line handle
    lineHandle = findobj(h, 'Type', 'Line');
    
    if isempty(lineHandle)
        error('NO DATA: Could not find an line object in the figure.')
    end
    
    xpts = get(lineHandle(1), 'XData');
    % if there are 35 points, label every one, otherwise label every other
    if length(xpts) == 35
        set(a, 'XTick', [1:35])
    else
        set(a, 'XTick', [1:2:70])
    end
    xticklabel_rotate([], 45, labels)
end